package encryption;

import java.io.*;
import java.net.*;
import java.security.*;
import javax.crypto.*;

public class CipherServer
{
    public static void main(String[] args) throws Exception 
    {
        int port = 7999;
        ServerSocket server = new ServerSocket(port);
        Socket s = server.accept();

        // -Read the key from the file generated by the client.
        ObjectInputStream in = new ObjectInputStream(new FileInputStream("KeyFile.xx"));
        Key key = (Key)in.readObject();
        System.out.println(key.getClass().getName());
        in.close();

        // -Use the key to decrypt the incoming message from socket s.      
        Cipher cipher = Cipher.getInstance("DES/ECB/PKCS5Padding");
        cipher.init(Cipher.DECRYPT_MODE, key);
        CipherInputStream cipherIn = new CipherInputStream(s.getInputStream(), cipher);
        byte[] stringInBytes = new byte[44];
        cipherIn.read(stringInBytes);
        String string = new String(stringInBytes);

        // -Print out the decrypt String to see if it matches the orignal message.
        System.out.println(string);
    }
}
