package encryption;

import java.io.*;
import java.net.*;
import java.security.*;
import javax.crypto.*;

public class CipherServer
{
    public static void main(String[] args) throws Exception 
    {
        int port = 7999;
        ServerSocket server = new ServerSocket(port);
        Socket s = server.accept();

        // -Read the key from the file generated by the client.
        ObjectInputStream in = new ObjectInputStream(new FileInputStream("KeyFile.xx"));
        Key key = (Key)in.readObject();
        in.close();

        // -Use the key to decrypt the incoming message from socket s.    
        Cipher cipher = Cipher.getInstance("DES/ECB/PKCS5Padding");
        cipher.init(Cipher.DECRYPT_MODE, key);

        DataInputStream dIn = new DataInputStream(s.getInputStream());
        int length = dIn.readInt();                    // read length of incoming message
        if(length>0) 
        {
            byte[] messageInBytes = new byte[length];
            dIn.readFully(messageInBytes, 0, messageInBytes.length); // read the message

            // -Print out the decrypt String to see if it matches the orignal message.
            System.out.println(new String(cipher.doFinal(messageInBytes)));
        }
    }
}
